### PR TITLE
dump_reachable_search_space: added option to stop generating states s…

### PR DESCRIPTION
**Pull request by drexlerd**
…tates when reaching a certain threshold

### CODE REVIEW

**Comment by jendrikseipp** [comment]
You're having a productive day on the road ;-) In which situation is it useful to try to expand the full state space, but still accept only a fragment of it if it's too big?

**Comment by drexlerd** [comment]
The problem is that we want to be able to filter instances that are too large. Hence, we need a stopping criteria to be able to not spend to much resources on huge instances.

**Comment by jendrikseipp** [comment]
But isn't a time limit better suited then?

**Comment by drexlerd** [comment]
Both are useful stopping criteria to me. I can add the time limit as well.

**Comment by jendrikseipp** [comment]
We decided offline that a time limit is the simpler option here.

**Pull request closed without merging**
